package obuchenie.IdeaIU;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by IntelliJ IDEA.
 * User: tor
 * Date: 23.05.11
 * Time: 19:09
 * To change this template use File | Settings | File Templates.
 */
public class FormGBL {
    private JPasswordField passwordField1;
    private JTextField textField1;
    private JButton canselButton;
    private JButton okButton;

    public FormGBL() {
        okButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                command_ok();
            }
        });
        canselButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                commang_cancel();
            }
        });
    }

    private void commang_cancel() {
        System.out.println("cancel pressed");
    }

    private void command_ok() {
        System.out.println("ok pressed");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16777216)), "Title", TitledBorder.CENTER, TitledBorder.BELOW_TOP));
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer1, gbc);
        passwordField1 = new JPasswordField();
        passwordField1.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 0);
        panel1.add(passwordField1, gbc);
        textField1 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridwidth = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 0, 0);
        panel1.add(textField1, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Pass");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(label1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer3, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Login");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(label2, gbc);
        okButton = new JButton();
        okButton.setLabel("Ok");
        okButton.setMaximumSize(new Dimension(65, 23));
        okButton.setMinimumSize(new Dimension(65, 23));
        okButton.setPreferredSize(new Dimension(65, 23));
        okButton.setText("Ok");
        okButton.setMnemonic('O');
        okButton.setDisplayedMnemonicIndex(0);
        okButton.setToolTipText("tipa ok");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 5;
        gbc.weightx = 0.1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(okButton, gbc);
        canselButton = new JButton();
        canselButton.setText("Cansel");
        canselButton.setMnemonic('C');
        canselButton.setDisplayedMnemonicIndex(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.gridheight = 2;
        gbc.weightx = 0.1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(3, 3, 3, 3);
        panel1.add(canselButton, gbc);
    }
}
