package com.tor.entity;

import javax.persistence.*;
import java.io.Serializable;

/**
 * User: tor
 * Date: 04.07.14
 * Time: 12:30
 */
@Entity
@Table(name = "books")
public class Book implements Serializable {
    private int id;
    private String name;
    private Publisher publisher;

    @Id               // mark id as primary key with autogenerated value
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "name", column = @Column(name = "Publisher")),
            @AttributeOverride(name = "address", column = @Column(name = "Publisher_Address"))

    })
    public Publisher getPublisher() {
        return publisher;
    }

    public void setPublisher(Publisher publisher) {
        this.publisher = publisher;
    }
}
